// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPvQXnKTZmv6FDi2Ci9gKN6LyBcsChhDI',
    appId: '1:99260951523:web:0c60238283a1cd21444ed6',
    messagingSenderId: '99260951523',
    projectId: 'uaetask-b3731',
    authDomain: 'uaetask-b3731.firebaseapp.com',
    storageBucket: 'uaetask-b3731.appspot.com',
    measurementId: 'G-FE6P7VJXE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpmAABRe4BLrKEqbBa9uM3KUGXc5tDujU',
    appId: '1:99260951523:android:dbbab2c4917b3ec6444ed6',
    messagingSenderId: '99260951523',
    projectId: 'uaetask-b3731',
    storageBucket: 'uaetask-b3731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnOWr7ZTSx63mu_Oc2P0hjfi2e95DYPtA',
    appId: '1:99260951523:ios:7869f8dc246a8d89444ed6',
    messagingSenderId: '99260951523',
    projectId: 'uaetask-b3731',
    storageBucket: 'uaetask-b3731.appspot.com',
    iosBundleId: 'com.example.uaeTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnOWr7ZTSx63mu_Oc2P0hjfi2e95DYPtA',
    appId: '1:99260951523:ios:7869f8dc246a8d89444ed6',
    messagingSenderId: '99260951523',
    projectId: 'uaetask-b3731',
    storageBucket: 'uaetask-b3731.appspot.com',
    iosBundleId: 'com.example.uaeTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPvQXnKTZmv6FDi2Ci9gKN6LyBcsChhDI',
    appId: '1:99260951523:web:13e7aa17b4d38e36444ed6',
    messagingSenderId: '99260951523',
    projectId: 'uaetask-b3731',
    authDomain: 'uaetask-b3731.firebaseapp.com',
    storageBucket: 'uaetask-b3731.appspot.com',
    measurementId: 'G-G180QRFHYE',
  );
}
